Advanced Building Blocks - Enumerables
Oxford-G/Ruby-Enumerables pull request #1
Opened 2020-12-07 10:16 UTC by Oxford-G

Building Ruby Enumrables

2020-12-07 17:28 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED 🛑 ♻️ 

Hello! ✋ 
A great effort in this project! 👍 
It is not easy to start working on Ruby with the enumerables! 🤦 
But you did a great job so far! 💯 
However, we still need to make some changes in order to get this project approved! 💪 
Kindly check my comments below 👇  implement the changes and request a new code review ⏩ 
## Mandatory changes
- README file:
    - Project description and built with sections must have the same header size as getting started, author...
    - In the author section, kindly add your LinkedIn profile
    - In the prerequisites section, for this project the user does not need a web browser, you can add instead something like, 'ruby version xxxx'
    - In the getting started section, if you do not want to change that line '$ git clone https://github.com/oxford-g/NYT-webpage-clone.git' make sure the user understands that must be a link similar to this
    - Fill up the about section in the Github page, and do not forget the tags, it will make it easier for the user to know what is the project about

2020-12-07 17:28 UTC, javitocor commented on main.rb
> +  end
- #my_each returns an Enumerator if no block is given, kindly fix that

2020-12-07 17:28 UTC, javitocor commented on main.rb
> +  end
- #my_each_with_index should return an enumerator if no block is given
- #my_each_with_index does not mutate the original array
- #my_each_with_index when a block is given when self is an array returns the array itself after calling the given block once for each element in self
- #my_each_with_index when a block is given when self is a range behaves like #each_with_index calls the given block once for each element in self
- #my_each_with_index when a block is given when self is a hash behaves like #each_with_index calls the given block once for each element in self
- #my_each_with_index when a block is given when self is an array behaves like #each_with_index calls the given block once for each element in self

2020-12-07 17:28 UTC, javitocor commented on main.rb
> +  end
- #my_select returns an enumerator if no block is given

2020-12-07 17:28 UTC, javitocor commented on main.rb
> +  end
- #my_any? when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern

2020-12-07 17:28 UTC, javitocor commented on main.rb
> +  end
- #my_count counts the number of elements yielding a true value if a block is given
- #my_count does not mutate the original array

2020-12-07 23:44 UTC, elmejdki requested changes
# status: require changes :recycle: 
## Great job @team :clap: :100: :+1:, Impresive work so far :100:, but we still have some changes :hammer: :wrench: :toolbox: to take care of.


Please check the comments below :point_down: :point_down: :point_down: :point_down: :point_down::

also please run your code and test it before you submit another code reivew.

### Please make all the required changes before you submit another code review.
## Happy Coding :tophat: 
_If you have a question or need help don't hesitate to contact me on slack._

2020-12-07 23:44 UTC, elmejdki commented on main.rb
> +  end
## my_each_with_index:

- [ ] You have an error in your my_each_with_index method, please fix it:

![image](https://user-images.githubusercontent.com/34653764/101418525-61da4b00-38ee-11eb-8915-aac71c0b57e8.png)

2020-12-08 10:10 UTC, ElijahTobs approved these changes
# Status: Approved! :tada: 

Congratulations! @Oxford-G 

Good job implementing the change as requested by the previous TSE.

## You can now merge and submit.

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

2020-12-18 10:59 UTC, merged